=begin
CodeSnip REST API

Development Pastebin with a twist.

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git


=end

module SwaggerClient
  VERSION = "1.0.0"
end
