//
// DefaultAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



public class DefaultAPI: APIBase {
    /**
     
     Creates a code snippet.
     
     - parameter codeSnippetBody: (body) Code snippet object.
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func snipPost(codeSnippetBody codeSnippetBody: CodeSnippet?, completion: ((error: ErrorType?) -> Void)) {
        snipPostWithRequestBuilder(codeSnippetBody: codeSnippetBody).execute { (response, error) -> Void in
            completion(error: error);
        }
    }


    /**
     
     Creates a code snippet.
     
     - POST /snip
     - Creates a code snippet in the specified language.
     
     - parameter codeSnippetBody: (body) Code snippet object.

     - returns: RequestBuilder<Void> 
     */
    public class func snipPostWithRequestBuilder(codeSnippetBody codeSnippetBody: CodeSnippet?) -> RequestBuilder<Void> {
        let path = "/snip"
        let URLString = SwaggerClientAPI.basePath + path
        
        let parameters = codeSnippetBody?.encodeToJSON() as? [String:AnyObject]

        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: parameters, isBody: true)
    }

    /**
     
     Retrieves the specified code snippet.
     
     - parameter codeSnippetUuid: (path) Code snippet unique identifier.
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func snipCodeSnippetUuidGet(codeSnippetUuid codeSnippetUuid: String, completion: ((data: CodeSnippet?, error: ErrorType?) -> Void)) {
        snipCodeSnippetUuidGetWithRequestBuilder(codeSnippetUuid: codeSnippetUuid).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     
     Retrieves the specified code snippet.
     
     - GET /snip/{codeSnippetUuid}
     - Retrieves the specified code snippet.
     - examples: [{contentType=application/json, example={
  "expires" : 123456789,
  "data" : "aeiou",
  "uuid" : "aeiou"
}}]
     
     - parameter codeSnippetUuid: (path) Code snippet unique identifier.

     - returns: RequestBuilder<CodeSnippet> 
     */
    public class func snipCodeSnippetUuidGetWithRequestBuilder(codeSnippetUuid codeSnippetUuid: String) -> RequestBuilder<CodeSnippet> {
        var path = "/snip/{codeSnippetUuid}"
        path = path.stringByReplacingOccurrencesOfString("{codeSnippetUuid}", withString: "\(codeSnippetUuid)", options: .LiteralSearch, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        
        let nillableParameters: [String:AnyObject?] = [:]
        let parameters = APIHelper.rejectNil(nillableParameters)

        let requestBuilder: RequestBuilder<CodeSnippet>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: parameters, isBody: true)
    }

    /**
     
     Updates a code snippet.
     
     - parameter codeSnippetUuid: (path) Code snippet unique identifier.
     - parameter codeSnippetBody: (body) Code snippet object.
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func snipCodeSnippetUuidPut(codeSnippetUuid codeSnippetUuid: String, codeSnippetBody: CodeSnippet?, completion: ((error: ErrorType?) -> Void)) {
        snipCodeSnippetUuidPutWithRequestBuilder(codeSnippetUuid: codeSnippetUuid, codeSnippetBody: codeSnippetBody).execute { (response, error) -> Void in
            completion(error: error);
        }
    }


    /**
     
     Updates a code snippet.
     
     - PUT /snip/{codeSnippetUuid}
     - Updates a code snippet changes.
     
     - parameter codeSnippetUuid: (path) Code snippet unique identifier.
     - parameter codeSnippetBody: (body) Code snippet object.

     - returns: RequestBuilder<Void> 
     */
    public class func snipCodeSnippetUuidPutWithRequestBuilder(codeSnippetUuid codeSnippetUuid: String, codeSnippetBody: CodeSnippet?) -> RequestBuilder<Void> {
        var path = "/snip/{codeSnippetUuid}"
        path = path.stringByReplacingOccurrencesOfString("{codeSnippetUuid}", withString: "\(codeSnippetUuid)", options: .LiteralSearch, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        
        let parameters = codeSnippetBody?.encodeToJSON() as? [String:AnyObject]

        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PUT", URLString: URLString, parameters: parameters, isBody: true)
    }

    /**
     
     Deletes the specified code snippet.
     
     - parameter codeSnippetUuid: (path) Code snippet unique identifier.
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func snipCodeSnippetUuidDelete(codeSnippetUuid codeSnippetUuid: String, completion: ((error: ErrorType?) -> Void)) {
        snipCodeSnippetUuidDeleteWithRequestBuilder(codeSnippetUuid: codeSnippetUuid).execute { (response, error) -> Void in
            completion(error: error);
        }
    }


    /**
     
     Deletes the specified code snippet.
     
     - DELETE /snip/{codeSnippetUuid}
     - Deletes the specified code snippet.
     
     - parameter codeSnippetUuid: (path) Code snippet unique identifier.

     - returns: RequestBuilder<Void> 
     */
    public class func snipCodeSnippetUuidDeleteWithRequestBuilder(codeSnippetUuid codeSnippetUuid: String) -> RequestBuilder<Void> {
        var path = "/snip/{codeSnippetUuid}"
        path = path.stringByReplacingOccurrencesOfString("{codeSnippetUuid}", withString: "\(codeSnippetUuid)", options: .LiteralSearch, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        
        let nillableParameters: [String:AnyObject?] = [:]
        let parameters = APIHelper.rejectNil(nillableParameters)

        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "DELETE", URLString: URLString, parameters: parameters, isBody: true)
    }

    /**
     
     Retrieves all code snippets.
     
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func snipsGet(completion: ((data: CodeSnippetList?, error: ErrorType?) -> Void)) {
        snipsGetWithRequestBuilder().execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     
     Retrieves all code snippets.
     
     - GET /snips
     - examples: [{contentType=application/json, example=""}]

     - returns: RequestBuilder<CodeSnippetList> 
     */
    public class func snipsGetWithRequestBuilder() -> RequestBuilder<CodeSnippetList> {
        let path = "/snips"
        let URLString = SwaggerClientAPI.basePath + path
        
        let nillableParameters: [String:AnyObject?] = [:]
        let parameters = APIHelper.rejectNil(nillableParameters)

        let requestBuilder: RequestBuilder<CodeSnippetList>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: parameters, isBody: true)
    }

}
