//
// CodeSnippet.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class CodeSnippet: JSONEncodable {

    /** Code snippet unique identifier. */
    public var uuid: String?
    /** Base64 encoded code snippet to store. */
    public var data: String?
    /** Expiration time in seconds since epoch (0 will live forever). */
    public var expires: Int?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["uuid"] = self.uuid
        nillableDictionary["data"] = self.data
        nillableDictionary["expires"] = self.expires
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
