=begin
CodeSnip REST API

Development Pastebin with a twist.

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git


=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CodeSnippetList' do
  before do
    # run before each test
    @instance = SwaggerClient::CodeSnippetList.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CodeSnippetList' do
    it 'should create an instact of CodeSnippetList' do
      @instance.should be_a(SwaggerClient::CodeSnippetList) 
    end
  end
end

