=begin
CodeSnip REST API

Development Pastebin with a twist.

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git


=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CodeSnippet' do
  before do
    # run before each test
    @instance = SwaggerClient::CodeSnippet.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CodeSnippet' do
    it 'should create an instact of CodeSnippet' do
      @instance.should be_a(SwaggerClient::CodeSnippet) 
    end
  end
  describe 'test attribute "uuid"' do
    it 'should work' do
       # assertion here
       # should be_a()
       # should be_nil
       # should ==
       # should_not ==
    end
  end

  describe 'test attribute "data"' do
    it 'should work' do
       # assertion here
       # should be_a()
       # should be_nil
       # should ==
       # should_not ==
    end
  end

  describe 'test attribute "expires"' do
    it 'should work' do
       # assertion here
       # should be_a()
       # should be_nil
       # should ==
       # should_not ==
    end
  end

end

